### ISSUE TITLE
display 'present' instead of dec 2099

### ISSUE THREAD

**Issue by tomdemeyer** [transparantnederland/relationizer#33]

**Comment by por** [comment]
Do you have a permalink to illustrate?

**Comment by por** [comment]
I found one: https://browse.transparantnederland.nl/#urn:hgid:pdc/01724_1999060719990608

> Commissioner of ENECO HOLDING N.V.
> Apr 2007 - Dec 2099 (93 years)

I do think this is the responsibility of the api though.
